"Domen Kožar":
  twitter: iElectric
  level: support
"Sam Stites":
  level: amazing
"Finpan Halpenny":
  level: support
"Josh Miller":
  level: support
"Josh Vera":
  level: amazing
"Shae Erisson":
  level: support
