---
title: in Code
development: no
description:
  Weblog of Justin Le, covering his various adventures in programming and
  explorations in the vast worlds of computation physics, and knowledge.
feed: http://feeds.feedburner.com/incodeblog
copyright: 2018 Justin Le
license: CC-BY-NC-ND 3.0
license-link: https://creativecommons.org/licenses/by-nc-nd/3.0/
author:
  name: Justin Le
  email: justin@jle.im
  rel: https://plus.google.com/107705320197444500140
  twitter: mstk
  gplus: +JustinLe
  github: mstksg
  linkedin: lejustin
  keybase: mstksg
  coinbase: mstksg
  btc: 3D7rmAYgbDnp4gp4rf22THsGt74fNucPDU
  patreon: justinle
  twitch: mstksg
blobs:
  tree: https://github.com/mstksg/inCode/tree
  source-branch: master
  render-branch: gh-pages
interactive-url: https://www.fpcomplete.com/user/jle/
code-samples: code-samples
host:
  secure: yes
  base: blog.jle.im
developer-apis:
  analytics:
    id: UA-443711-8
    domain: jle.im
  disqus: incode
  facebook: "641852699171929"
  add-this: ra-5234d67a6b68dcd4
  feedburner: incodeblog
  flattr: 3p9jqr
preferences:
  slug-length: 8
  home-entries: 8
  lede-max: 6
  feed-entries: 10
  sidebar-entries: 5
...
